apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "k8sprod-ca23"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "k8sprod-ca23"
    spec:
      containers:
        - name: "k8sprod-ca23"
          image: "testk8sfirst.azurecr.io/k8sprod"
          ports:
          - containerPort: 5000