apiVersion: v1
kind: Service
metadata:
    name: "k8sprod-ca23"
    labels:
        app: "k8sprod-ca23"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "k8sprod-ca23"